services:
  postgres:
    image: postgres:18
    container_name: my-postgres-task2
    environment:
      POSTGRES_PASSWORD: superuserpass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pinger:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: pg-pinger:1.0
    env_file:
      - .env
    depends_on:
      - postgres

  postgres-task3:
    image: postgres:18
    container_name: my-postgres-task3
    environment:
      POSTGRES_PASSWORD: superuserpass
      POSTGRES_DB: shop
    ports:
      - "5434:5432"
    volumes:
      - pgdata3:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d:ro
  crud:
    build:
      context: .
      dockerfile: docker/Dockerfile.crud
    image: pg-crud:1.0
    env_file:
      - .env.crud
    depends_on:
      - postgres-task3
    stdin_open: true
    tty: true

volumes:
  pgdata2:
  pgdata3: